/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NewsRouteImport } from './routes/news'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as QuotesIndexRouteImport } from './routes/quotes.index'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/banners': typeof BannersRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/references': typeof ReferencesRoute
  '/reporting': typeof ReportingRoute
  '/settings': typeof SettingsRoute
  '/solutions': typeof SolutionsRoute
  '/users': typeof UsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/banners': typeof BannersRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/references': typeof ReferencesRoute
  '/reporting': typeof ReportingRoute
  '/settings': typeof SettingsRoute
  '/solutions': typeof SolutionsRoute
  '/users': typeof UsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/clients': typeof ClientsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/quotes': typeof QuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/banners': typeof BannersRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/documents': typeof DocumentsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/newsletter': typeof NewsletterRoute
  '/notifications': typeof NotificationsRoute
  '/promotions': typeof PromotionsRoute
  '/references': typeof ReferencesRoute
  '/reporting': typeof ReportingRoute
  '/settings': typeof SettingsRoute
  '/solutions': typeof SolutionsRoute
  '/users': typeof UsersRoute
  '/clients/$id': typeof ClientsIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/banners'
    | '/brands'
    | '/categories'
    | '/documents'
    | '/forms'
    | '/login'
    | '/media'
    | '/news'
    | '/newsletter'
    | '/notifications'
    | '/promotions'
    | '/references'
    | '/reporting'
    | '/settings'
    | '/solutions'
    | '/users'
    | '/clients/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/quotes/$id'
    | '/clients/'
    | '/orders/'
    | '/products/'
    | '/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/banners'
    | '/brands'
    | '/categories'
    | '/documents'
    | '/forms'
    | '/login'
    | '/media'
    | '/news'
    | '/newsletter'
    | '/notifications'
    | '/promotions'
    | '/references'
    | '/reporting'
    | '/settings'
    | '/solutions'
    | '/users'
    | '/clients/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/quotes/$id'
    | '/clients'
    | '/orders'
    | '/products'
    | '/quotes'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/banners'
    | '/brands'
    | '/categories'
    | '/documents'
    | '/forms'
    | '/login'
    | '/media'
    | '/news'
    | '/newsletter'
    | '/notifications'
    | '/promotions'
    | '/references'
    | '/reporting'
    | '/settings'
    | '/solutions'
    | '/users'
    | '/clients/$id'
    | '/orders/$id'
    | '/products/$id'
    | '/quotes/$id'
    | '/clients/'
    | '/orders/'
    | '/products/'
    | '/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BannersRoute: typeof BannersRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  DocumentsRoute: typeof DocumentsRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  NewsletterRoute: typeof NewsletterRoute
  NotificationsRoute: typeof NotificationsRoute
  PromotionsRoute: typeof PromotionsRoute
  ReferencesRoute: typeof ReferencesRoute
  ReportingRoute: typeof ReportingRoute
  SettingsRoute: typeof SettingsRoute
  SolutionsRoute: typeof SolutionsRoute
  UsersRoute: typeof UsersRoute
  ClientsIdRoute: typeof ClientsIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  QuotesIdRoute: typeof QuotesIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BannersRoute: BannersRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  DocumentsRoute: DocumentsRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  NewsletterRoute: NewsletterRoute,
  NotificationsRoute: NotificationsRoute,
  PromotionsRoute: PromotionsRoute,
  ReferencesRoute: ReferencesRoute,
  ReportingRoute: ReportingRoute,
  SettingsRoute: SettingsRoute,
  SolutionsRoute: SolutionsRoute,
  UsersRoute: UsersRoute,
  ClientsIdRoute: ClientsIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  QuotesIdRoute: QuotesIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
